# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcoreaddons' : '@stable'
    'frameworks/ki18n' : '@stable'
    'frameworks/kirigami' : '@stable'
    'frameworks/prison' : '@stable'
    'pim/khealthcertificate' : '@stable'
    'pim/kitinerary' : '@stable'
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Android/Qt6', 'Windows/Qt6']
  'require':
    'pim/kitinerary' : '@latest'
