# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Android', 'Windows']
  'require':
    'frameworks/kcoreaddons' : '@latest-kf6'
    'frameworks/ki18n' : '@latest-kf6'
    'frameworks/kirigami' : '@latest-kf6'
    'frameworks/kconfig' : '@latest-kf6'
    'frameworks/prison' : '@latest-kf6'
    'pim/khealthcertificate' : '@latest-kf6'
    'pim/kitinerary' : '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux' ]
